### PR TITLE
Add the fndef macro that defines an uninterpreted spec function (with no body)

### PR DESCRIPTION
**Pull request by utaal**
Following up from @tjhance and @Chris-Hawblitzel's conversation about these functions.

### CODE REVIEW

**Comment by tjhance** [comment]
I like the idea! Maybe we should do something with the word `trusted` in it? maybe like `trusted_fn!`

**Comment by tjhance** [comment]
also, is there a reason it's a proc_macro?

**Comment by utaal** [comment]
The idea is to use this for pure uninterpreted functions, which I don’t think count as trusted per se. What’s trusted are the axioms that give them meaning, potentially.

proc macro because there’s no capture in macro_rules that matches just a function decl apparently?

**Comment by tjhance** [comment]
did you try the `tt` type? I think it supports arbitrary token streams

**Comment by utaal** [comment]
Tried, it apparently supports _some_ token streams (I actually failed at finding an authoritative answer to what exactly it matches). :/

**Comment by tjhance** [comment]
Ah well, proc macro it is then

**Comment by utaal** [comment]
> pure uninterpreted functions

I'm now thinking this should be called `fndecl!`

**Review by tjhance — APPROVED** [review]

**Review by Chris-Hawblitzel — APPROVED** [review]

**Pull request merged**
