### PR TITLE
Add --verify-function option

### PR DESCRIPTION
**Pull request by Chris-Hawblitzel**
Verify just a single function.

Example: rust_verify ... vectors.rs --verify-root --verify-function binary_search

### CODE REVIEW

**Comment by parno** [comment]
Does `--verify-function` require `--verify-root`, or are they orthogonal?

**Comment by Chris-Hawblitzel** [comment]
> Does `--verify-function` require `--verify-root`, or are they orthogonal?

It requires `--verify-root` or `--verify-module`.  It will print an error if one of these is not specified.  The name of the function is relative to the module being verified.

**Comment by parno** [comment]
Cool, got it -- thanks!

**Review by utaal — APPROVED** [review]
With these changes https://github.com/secure-foundations/verus/pull/150 if they look good to you (merge https://github.com/secure-foundations/verus/pull/150 into this first).

**Pull request merged**
